name: Create min js
on:
  workflow_dispatch

jobs:
  minify_js:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - uses: actions/checkout@v2

      - name: Cleanup existing minified js
        run: for f in *.min.js; do [ -e "${f%.*}.js" ] && rm "$f"; done
        shell: bash

      - name: Auto Minify
        uses: nizarmah/auto-minify@master

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
            commit_message: "Github Action: Auto Minified JS files"
            branch: ${{ github.ref }}